let cables =  [
      {
        "id": 8,
        "biller_code": "BIL137",
        "name": "DSTV Payment",
        "default_commission": 0,
        "date_added": "2018-08-17T00:00:00Z",
        "country": "GH",
        "is_airtime": false,
        "biller_name": "DSTV",
        "item_code": "CB226",
        "short_name": "DSTV",
        "fee": 0,
        "commission_on_fee": false,
        "label_name": "Smart card Number",
        "amount": 0
      },
      {
        "id": 255,
        "biller_code": "BIL156",
        "name": "DSTV Compact Plus",
        "default_commission": 0.1,
        "date_added": "2019-07-29T18:13:28.023Z",
        "country": "UG",
        "is_airtime": false,
        "biller_name": "DSTV Compact Plus",
        "item_code": "CB281",
        "short_name": "Compact Plus",
        "fee": 100,
        "commission_on_fee": true,
        "label_name": "SmartCard Number",
        "amount": 180000
      },
      {
        "id": 256,
        "biller_code": "BIL156",
        "name": "DSTV Family Uganda",
        "default_commission": 0.1,
        "date_added": "2019-07-29T18:13:28.023Z",
        "country": "UG",
        "is_airtime": false,
        "biller_name": "DSTV Family Uganda",
        "item_code": "CB282",
        "short_name": "Family",
        "fee": 100,
        "commission_on_fee": true,
        "label_name": "SmartCard Number",
        "amount": 60000
      },
      {
        "id": 257,
        "biller_code": "BIL156",
        "name": "DSTV Access Uganda",
        "default_commission": 0.1,
        "date_added": "2019-07-29T18:13:28.023Z",
        "country": "UG",
        "is_airtime": false,
        "biller_name": "DSTV Access Uganda",
        "item_code": "CB283",
        "short_name": "Access",
        "fee": 100,
        "commission_on_fee": true,
        "label_name": "SmartCard Number",
        "amount": 33000
      },
      {
        "id": 258,
        "biller_code": "BIL157",
        "name": "GOTV Light (Monthly)",
        "default_commission": 0.1,
        "date_added": "2019-07-29T18:13:28.023Z",
        "country": "UG",
        "is_airtime": false,
        "biller_name": "GOTV Light (Monthly)",
        "item_code": "CB284",
        "short_name": "GOTV Light (Monthly)",
        "fee": 100,
        "commission_on_fee": true,
        "label_name": "SmartCard Number",
        "amount": 11000
      },
      {
        "id": 259,
        "biller_code": "BIL157",
        "name": "GOTV PLUS",
        "default_commission": 0.1,
        "date_added": "2019-07-29T18:13:28.023Z",
        "country": "UG",
        "is_airtime": false,
        "biller_name": "GOTV PLUS",
        "item_code": "CB285",
        "short_name": "GOTV PLUS",
        "fee": 100,
        "commission_on_fee": true,
        "label_name": "SmartCard Number",
        "amount": 28000
      },
      {
        "id": 260,
        "biller_code": "BIL157",
        "name": "GOTV MAX",
        "default_commission": 0.1,
        "date_added": "2019-07-29T18:13:28.023Z",
        "country": "UG",
        "is_airtime": false,
        "biller_name": "GOTV MAX",
        "item_code": "CB286",
        "short_name": "GOTV MAX",
        "fee": 100,
        "commission_on_fee": true,
        "label_name": "SmartCard Number",
        "amount": 39000
      },
      {
        "id": 261,
        "biller_code": "BIL157",
        "name": "Gotv Value",
        "default_commission": 0.1,
        "date_added": "2019-07-29T18:13:28.023Z",
        "country": "UG",
        "is_airtime": false,
        "biller_name": "Gotv Value",
        "item_code": "CB287",
        "short_name": "Gotv Value",
        "fee": 100,
        "commission_on_fee": true,
        "label_name": "SmartCard Number",
        "amount": 16000
      },
      {
        "id": 262,
        "biller_code": "BIL160",
        "name": "Startime Basic",
        "default_commission": 0.1,
        "date_added": "2019-07-29T18:13:28.023Z",
        "country": "UG",
        "is_airtime": false,
        "biller_name": "Startime Basic",
        "item_code": "CB291",
        "short_name": "Startime Basic",
        "fee": 100,
        "commission_on_fee": true,
        "label_name": "SmartCard Number",
        "amount": 1300
      },
      {
        "id": 263,
        "biller_code": "BIL160",
        "name": "Startime Classic",
        "default_commission": 0.1,
        "date_added": "2019-07-29T18:13:28.023Z",
        "country": "UG",
        "is_airtime": false,
        "biller_name": "Startime Classic",
        "item_code": "CB292",
        "short_name": "Startime Classic",
        "fee": 100,
        "commission_on_fee": true,
        "label_name": "SmartCard Number",
        "amount": 1900
      },
      {
        "id": 287,
        "biller_code": "BIL121",
        "name": "DSTV COMPACT",
        "default_commission": 0.3,
        "date_added": "2020-02-11T11:13:29.62Z",
        "country": "NG",
        "is_airtime": false,
        "biller_name": "DSTV COMPACT",
        "item_code": "CB177",
        "short_name": "DSTV COMPACT",
        "fee": 100,
        "commission_on_fee": true,
        "label_name": "SmartCard Number",
        "amount": 7900
      },
      {
        "id": 288,
        "biller_code": "BIL121",
        "name": "DSTV COMPACT + HD",
        "default_commission": 0.3,
        "date_added": "2020-02-11T11:13:29.62Z",
        "country": "NG",
        "is_airtime": false,
        "biller_name": "DSTV COMPACT + HD",
        "item_code": "CB178",
        "short_name": "DSTV COMPACT + HD",
        "fee": 100,
        "commission_on_fee": true,
        "label_name": "SmartCard Number",
        "amount": 10400
      },
      {
        "id": 289,
        "biller_code": "BIL121",
        "name": "DSTV COMPACT PLUS",
        "default_commission": 0.3,
        "date_added": "2020-02-11T11:13:29.62Z",
        "country": "NG",
        "is_airtime": false,
        "biller_name": "DSTV COMPACT PLUS",
        "item_code": "CB179",
        "short_name": "DSTV COMPACT PLUS",
        "fee": 100,
        "commission_on_fee": true,
        "label_name": "SmartCard Number",
        "amount": 12400
      },
      {
        "id": 290,
        "biller_code": "BIL121",
        "name": "DSTV COMPACT PLUS + ASIA",
        "default_commission": 0.3,
        "date_added": "2020-02-11T11:13:29.62Z",
        "country": "NG",
        "is_airtime": false,
        "biller_name": "DSTV COMPACT PLUS + ASIA",
        "item_code": "CB180",
        "short_name": "DSTV COMPACT PLUS + ASIA",
        "fee": 100,
        "commission_on_fee": true,
        "label_name": "SmartCard Number",
        "amount": 18600
      },
      {
        "id": 291,
        "biller_code": "BIL121",
        "name": "DSTV COMPACT PLUS + HD",
        "default_commission": 0.3,
        "date_added": "2020-02-11T11:13:29.62Z",
        "country": "NG",
        "is_airtime": false,
        "biller_name": "DSTV COMPACT PLUS + HD",
        "item_code": "CB181",
        "short_name": "DSTV COMPACT PLUS + HD",
        "fee": 100,
        "commission_on_fee": true,
        "label_name": "SmartCard Number",
        "amount": 14900
      },
      {
        "id": 292,
        "biller_code": "BIL121",
        "name": "DSTV PREMIUM",
        "default_commission": 0.3,
        "date_added": "2020-02-11T11:13:29.62Z",
        "country": "NG",
        "is_airtime": false,
        "biller_name": "DSTV PREMIUM",
        "item_code": "CB182",
        "short_name": "DSTV PREMIUM",
        "fee": 100,
        "commission_on_fee": true,
        "label_name": "SmartCard Number",
        "amount": 18400
      },
      {
        "id": 293,
        "biller_code": "BIL121",
        "name": "DSTV PREMIUM ASIA",
        "default_commission": 0.3,
        "date_added": "2020-02-11T11:13:29.62Z",
        "country": "NG",
        "is_airtime": false,
        "biller_name": "DSTV PREMIUM ASIA",
        "item_code": "CB183",
        "short_name": "DSTV PREMIUM ASIA",
        "fee": 100,
        "commission_on_fee": true,
        "label_name": "SmartCard Number",
        "amount": 17700
      },
      {
        "id": 294,
        "biller_code": "BIL121",
        "name": "DSTV PREMIUM + HD",
        "default_commission": 0.3,
        "date_added": "2020-02-11T11:13:29.62Z",
        "country": "NG",
        "is_airtime": false,
        "biller_name": "DSTV PREMIUM + HD",
        "item_code": "CB184",
        "short_name": "DSTV PREMIUM + HD",
        "fee": 100,
        "commission_on_fee": true,
        "label_name": "SmartCard Number",
        "amount": 20900
      },
      {
        "id": 295,
        "biller_code": "BIL121",
        "name": "DSTV Box Office bill",
        "default_commission": 0.3,
        "date_added": "2020-02-11T11:13:29.62Z",
        "country": "NG",
        "is_airtime": false,
        "biller_name": "DSTV BOX OFFICE",
        "item_code": "CB221",
        "short_name": "DSTV BOX OFFICE",
        "fee": 100,
        "commission_on_fee": true,
        "label_name": "SmartCard Number",
        "amount": 0
      },
      {
        "id": 296,
        "biller_code": "BIL122",
        "name": "GOTV LIGHT",
        "default_commission": 0.3,
        "date_added": "2020-02-11T11:13:29.62Z",
        "country": "NG",
        "is_airtime": false,
        "biller_name": "GOTV LIGHT",
        "item_code": "CB185",
        "short_name": "GOTV LIGHT",
        "fee": 100,
        "commission_on_fee": true,
        "label_name": "SmartCard Number",
        "amount": 410
      },
      {
        "id": 299,
        "biller_code": "BIL122",
        "name": "GOTV MAX",
        "default_commission": 0.3,
        "date_added": "2020-02-11T11:13:29.62Z",
        "country": "NG",
        "is_airtime": false,
        "biller_name": "GOTV MAX",
        "item_code": "CB188",
        "short_name": "GOTV MAX",
        "fee": 100,
        "commission_on_fee": true,
        "label_name": "SmartCard Number",
        "amount": 3600
      },
      {
        "id": 300,
        "biller_code": "BIL123",
        "name": "NOVA - One Day",
        "default_commission": 0.3,
        "date_added": "2020-02-11T11:13:29.62Z",
        "country": "NG",
        "is_airtime": false,
        "biller_name": "NOVA - One Day",
        "item_code": "CB189",
        "short_name": "NOVA - One Day",
        "fee": 100,
        "commission_on_fee": true,
        "label_name": "SmartCard Number",
        "amount": 60
      },
      {
        "id": 301,
        "biller_code": "BIL123",
        "name": "NOVA - One Week",
        "default_commission": 0.3,
        "date_added": "2020-02-11T11:13:29.62Z",
        "country": "NG",
        "is_airtime": false,
        "biller_name": "NOVA - One Week",
        "item_code": "CB190",
        "short_name": "NOVA - One Week",
        "fee": 100,
        "commission_on_fee": true,
        "label_name": "SmartCard Number",
        "amount": 300
      },
      {
        "id": 302,
        "biller_code": "BIL123",
        "name": "NOVA - One Month",
        "default_commission": 0.3,
        "date_added": "2020-02-11T11:13:29.62Z",
        "country": "NG",
        "is_airtime": false,
        "biller_name": "NOVA - One Month",
        "item_code": "CB191",
        "short_name": "NOVA - One Month",
        "fee": 100,
        "commission_on_fee": true,
        "label_name": "SmartCard Number",
        "amount": 900
      },
      {
        "id": 303,
        "biller_code": "BIL123",
        "name": "BASIC - One Day",
        "default_commission": 0.3,
        "date_added": "2020-02-11T11:13:29.62Z",
        "country": "NG",
        "is_airtime": false,
        "biller_name": "BASIC - One Day",
        "item_code": "CB192",
        "short_name": "BASIC - One Day",
        "fee": 100,
        "commission_on_fee": true,
        "label_name": "SmartCard Number",
        "amount": 90
      },
      {
        "id": 304,
        "biller_code": "BIL123",
        "name": "BASIC - One Week",
        "default_commission": 0.3,
        "date_added": "2020-02-11T11:13:29.62Z",
        "country": "NG",
        "is_airtime": false,
        "biller_name": "BASIC - One Week",
        "item_code": "CB193",
        "short_name": "BASIC - One Week",
        "fee": 100,
        "commission_on_fee": true,
        "label_name": "SmartCard Number",
        "amount": 450
      },
      {
        "id": 305,
        "biller_code": "BIL123",
        "name": "Startimes basic One Month",
        "default_commission": 0.3,
        "date_added": "2020-02-11T11:13:29.62Z",
        "country": "NG",
        "is_airtime": false,
        "biller_name": "BASIC - One Month",
        "item_code": "CB260",
        "short_name": "BASIC - One Month",
        "fee": 100,
        "commission_on_fee": true,
        "label_name": "SmartCard Number",
        "amount": 1300
      },
      {
        "id": 306,
        "biller_code": "BIL123",
        "name": "Startimes smart one day payment",
        "default_commission": 0.3,
        "date_added": "2020-02-11T11:13:29.62Z",
        "country": "NG",
        "is_airtime": false,
        "biller_name": "SMART - One Day",
        "item_code": "CB261",
        "short_name": "SMART - One Day",
        "fee": 100,
        "commission_on_fee": true,
        "label_name": "SmartCard Number",
        "amount": 120
      },
      {
        "id": 307,
        "biller_code": "BIL123",
        "name": "Startimes smart one week payment",
        "default_commission": 0.3,
        "date_added": "2020-02-11T11:13:29.62Z",
        "country": "NG",
        "is_airtime": false,
        "biller_name": "SMART - One Week",
        "item_code": "CB262",
        "short_name": "SMART - One Week",
        "fee": 100,
        "commission_on_fee": true,
        "label_name": "SmartCard Number",
        "amount": 600
      },
      {
        "id": 308,
        "biller_code": "BIL123",
        "name": "Startimes smart one month payment",
        "default_commission": 0.3,
        "date_added": "2020-02-11T11:13:29.62Z",
        "country": "NG",
        "is_airtime": false,
        "biller_name": "SMART - One Month",
        "item_code": "CB263",
        "short_name": "SMART - One Month",
        "fee": 100,
        "commission_on_fee": true,
        "label_name": "SmartCard Number",
        "amount": 1900
      },
      {
        "id": 309,
        "biller_code": "BIL123",
        "name": "Startimes classic one day payment",
        "default_commission": 0.3,
        "date_added": "2020-02-11T11:13:29.62Z",
        "country": "NG",
        "is_airtime": false,
        "biller_name": "CLASSIC - One Day",
        "item_code": "CB264",
        "short_name": "CLASSIC - One Day",
        "fee": 100,
        "commission_on_fee": true,
        "label_name": "SmartCard Number",
        "amount": 180
      },
      {
        "id": 310,
        "biller_code": "BIL123",
        "name": "Startimes classic one week payment",
        "default_commission": 0.3,
        "date_added": "2020-02-11T11:13:29.62Z",
        "country": "NG",
        "is_airtime": false,
        "biller_name": "CLASSIC - One Week",
        "item_code": "CB265",
        "short_name": "CLASSIC - One Week",
        "fee": 100,
        "commission_on_fee": true,
        "label_name": "SmartCard Number",
        "amount": 900
      },
      {
        "id": 311,
        "biller_code": "BIL123",
        "name": "Startimes classic one month payment",
        "default_commission": 0.3,
        "date_added": "2020-02-11T11:13:29.62Z",
        "country": "NG",
        "is_airtime": false,
        "biller_name": "CLASSIC - One month",
        "item_code": "CB266",
        "short_name": "CLASSIC - One month",
        "fee": 100,
        "commission_on_fee": true,
        "label_name": "SmartCard Number",
        "amount": 2600
      },
      {
        "id": 312,
        "biller_code": "BIL123",
        "name": "Startimes unique one day payment",
        "default_commission": 0.3,
        "date_added": "2020-02-11T11:13:29.62Z",
        "country": "NG",
        "is_airtime": false,
        "biller_name": "UNIQUE - One Day",
        "item_code": "CB267",
        "short_name": "UNIQUE - One Day",
        "fee": 100,
        "commission_on_fee": true,
        "label_name": "SmartCard Number",
        "amount": 240
      },
      {
        "id": 313,
        "biller_code": "BIL123",
        "name": "Startimes unique one week payment",
        "default_commission": 0.3,
        "date_added": "2020-02-11T11:13:29.62Z",
        "country": "NG",
        "is_airtime": false,
        "biller_name": "UNIQUE - One Week",
        "item_code": "CB268",
        "short_name": "UNIQUE - One Week",
        "fee": 100,
        "commission_on_fee": true,
        "label_name": "SmartCard Number",
        "amount": 1300
      },
      {
        "id": 314,
        "biller_code": "BIL123",
        "name": "Startimes unique one month payment",
        "default_commission": 0.3,
        "date_added": "2020-02-11T11:13:29.62Z",
        "country": "NG",
        "is_airtime": false,
        "biller_name": "UNIQUE - One Month",
        "item_code": "CB269",
        "short_name": "UNIQUE - One Month",
        "fee": 100,
        "commission_on_fee": true,
        "label_name": "SmartCard Number",
        "amount": 3800
      },
      {
        "id": 315,
        "biller_code": "BIL123",
        "name": "Startimes super one day payment",
        "default_commission": 0.3,
        "date_added": "2020-02-11T11:13:29.62Z",
        "country": "NG",
        "is_airtime": false,
        "biller_name": "SUPER - One Day",
        "item_code": "CB270",
        "short_name": "SUPER - One Day",
        "fee": 100,
        "commission_on_fee": true,
        "label_name": "SmartCard Number",
        "amount": 240
      },
      {
        "id": 316,
        "biller_code": "BIL123",
        "name": "Startimes super one week payment",
        "default_commission": 0.3,
        "date_added": "2020-02-11T11:13:29.62Z",
        "country": "NG",
        "is_airtime": false,
        "biller_name": "SUPER - One Week",
        "item_code": "CB271",
        "short_name": "SUPER - One Week",
        "fee": 100,
        "commission_on_fee": true,
        "label_name": "SmartCard Number",
        "amount": 1200
      },
      {
        "id": 317,
        "biller_code": "BIL123",
        "name": "Startimes super one month payment",
        "default_commission": 0.3,
        "date_added": "2020-02-11T11:13:29.62Z",
        "country": "NG",
        "is_airtime": false,
        "biller_name": "SUPER - One Month",
        "item_code": "CB272",
        "short_name": "SUPER - One Month",
        "fee": 100,
        "commission_on_fee": true,
        "label_name": "SmartCard Number",
        "amount": 3800
      },
      {
        "id": 16865,
        "biller_code": "BIL190",
        "name": "DSTV Payment",
        "default_commission": 0.1,
        "date_added": "2020-04-26T20:01:35.043Z",
        "country": "KE",
        "is_airtime": false,
        "biller_name": "DSTV Payment",
        "item_code": "CB500",
        "short_name": "DSTV Payment",
        "fee": 20,
        "commission_on_fee": true,
        "label_name": "Smart card Number",
        "amount": 0
      },
      {
        "id": 16866,
        "biller_code": "BIL192",
        "name": "GOTV Payment",
        "default_commission": 0.1,
        "date_added": "2020-04-26T20:01:35.043Z",
        "country": "KE",
        "is_airtime": false,
        "biller_name": "GOTV Payment",
        "item_code": "CB503",
        "short_name": "GOTV Payment",
        "fee": 20,
        "commission_on_fee": true,
        "label_name": "Smart card Number",
        "amount": 0
      },
      {
        "id": 16867,
        "biller_code": "BIL193",
        "name": "STARTIMES Payment",
        "default_commission": 0.1,
        "date_added": "2020-04-26T20:01:35.043Z",
        "country": "KE",
        "is_airtime": false,
        "biller_name": "STARTIMES Payment",
        "item_code": "CB504",
        "short_name": "STARTIMES Payment",
        "fee": 20,
        "commission_on_fee": true,
        "label_name": "Smart card Number",
        "amount": 0
      },
      {
        "id": 16889,
        "biller_code": "BIL121",
        "name": "DStv Yanga",
        "default_commission": 0.3,
        "date_added": "2020-02-11T11:13:29.62Z",
        "country": "NG",
        "is_airtime": false,
        "biller_name": "DStv Yanga",
        "item_code": "CB482",
        "short_name": "DStv Yanga",
        "fee": 100,
        "commission_on_fee": true,
        "label_name": "SmartCard Number",
        "amount": 2565
      },
      {
        "id": 16894,
        "biller_code": "BIL121",
        "name": "DStv Confam",
        "default_commission": 0.3,
        "date_added": "2020-02-11T11:13:29.62Z",
        "country": "NG",
        "is_airtime": false,
        "biller_name": "DStv Confam",
        "item_code": "CB483",
        "short_name": "DStv Confam",
        "fee": 100,
        "commission_on_fee": true,
        "label_name": "SmartCard Number",
        "amount": 4620
      },
      {
        "id": 16895,
        "biller_code": "BIL121",
        "name": "DStv Yanga + XTRA VIEW",
        "default_commission": 0.3,
        "date_added": "2020-02-11T11:13:29.62Z",
        "country": "NG",
        "is_airtime": false,
        "biller_name": "DStv Yanga + XTRA VIEW",
        "item_code": "CB484",
        "short_name": "DStv Yanga + XTRA VIEW",
        "fee": 100,
        "commission_on_fee": true,
        "label_name": "SmartCard Number",
        "amount": 5065
      },
      {
        "id": 16896,
        "biller_code": "BIL121",
        "name": "DStv Confam Bouquet E36 + XTRA VIEW",
        "default_commission": 0.3,
        "date_added": "2020-02-11T11:13:29.62Z",
        "country": "NG",
        "is_airtime": false,
        "biller_name": "DStv Confam Bouquet E36 + XTRA VIEW",
        "item_code": "CB485",
        "short_name": "DStv Confam Bouquet E36 + XTRA VIEW",
        "fee": 100,
        "commission_on_fee": true,
        "label_name": "SmartCard Number",
        "amount": 7115
      },
      {
        "id": 16897,
        "biller_code": "BIL122",
        "name": "GOtv Jinja",
        "default_commission": 0.3,
        "date_added": "2020-02-11T11:13:29.62Z",
        "country": "NG",
        "is_airtime": false,
        "biller_name": "GOtv Jinja",
        "item_code": "CB486",
        "short_name": "GOtv Jinja",
        "fee": 100,
        "commission_on_fee": true,
        "label_name": "SmartCard Number",
        "amount": 1640
      },
      {
        "id": 16898,
        "biller_code": "BIL122",
        "name": "GOtv Jolli",
        "default_commission": 0.3,
        "date_added": "2020-02-11T11:13:29.62Z",
        "country": "NG",
        "is_airtime": false,
        "biller_name": "GOtv Jolli",
        "item_code": "CB487",
        "short_name": "GOtv Jolli",
        "fee": 100,
        "commission_on_fee": true,
        "label_name": "SmartCard Number",
        "amount": 2460
      },
      {
        "id": 16899,
        "biller_code": "BIL121",
        "name": "Compact Plus + Asia +Xtraview",
        "default_commission": 0.3,
        "date_added": "2020-06-01T00:00:00Z",
        "country": "NG",
        "is_airtime": false,
        "biller_name": "Compact Plus + Asia +Xtraview",
        "item_code": "CB509",
        "short_name": "Compact Plus + Asia +Xtraview",
        "fee": 100,
        "commission_on_fee": true,
        "label_name": "Smartcard Number",
        "amount": 21100
      },
      {
        "id": 16903,
        "biller_code": "BIL121",
        "name": "Compact Plus + French Touch",
        "default_commission": 0.3,
        "date_added": "2020-02-11T11:13:29.62Z",
        "country": "NG",
        "is_airtime": false,
        "biller_name": "Compact Plus + French Touch",
        "item_code": "CB510",
        "short_name": "Compact Plus + French Touch",
        "fee": 100,
        "commission_on_fee": true,
        "label_name": "SmartCard Number",
        "amount": 14700
      },
      {
        "id": 16904,
        "biller_code": "BIL121",
        "name": "Compact Plus + French Plus",
        "default_commission": 0.3,
        "date_added": "2020-02-11T11:13:29.62Z",
        "country": "NG",
        "is_airtime": false,
        "biller_name": "Compact Plus + French Plus",
        "item_code": "CB511",
        "short_name": "Compact Plus + French Plus",
        "fee": 100,
        "commission_on_fee": true,
        "label_name": "SmartCard Number",
        "amount": 20500
      },
      {
        "id": 16905,
        "biller_code": "BIL121",
        "name": "DSTV PADI",
        "default_commission": 0.3,
        "date_added": "2020-02-11T11:13:29.62Z",
        "country": "NG",
        "is_airtime": false,
        "biller_name": "DSTV PADI",
        "item_code": "CB512",
        "short_name": "DSTV PADI",
        "fee": 100,
        "commission_on_fee": true,
        "label_name": "SmartCard Number",
        "amount": 1850
      },
      {
        "id": 16906,
        "biller_code": "BIL121",
        "name": "DSTV PADI + XTRA VIEW",
        "default_commission": 0.3,
        "date_added": "2020-02-11T11:13:29.62Z",
        "country": "NG",
        "is_airtime": false,
        "biller_name": "DSTV PADI + XTRA VIEW",
        "item_code": "Cb513",
        "short_name": "DSTV PADI + XTRA VIEW",
        "fee": 100,
        "commission_on_fee": true,
        "label_name": "SmartCard Number",
        "amount": 4350
      },
      {
        "id": 16907,
        "biller_code": "BIL121",
        "name": "DSTV Payment",
        "default_commission": 0.3,
        "date_added": "2020-06-05T22:07:22.593Z",
        "country": "NG",
        "is_airtime": false,
        "biller_name": "DSTV",
        "item_code": "CB182",
        "short_name": "DSTV",
        "fee": 100,
        "commission_on_fee": true,
        "label_name": "Smartcard Number",
        "amount": 0
      }
    ]

    export default cables
  