let internet = [
    {
      "id": 432,
      "biller_code": "BIL125",
      "name": "TOP UP ACCOUNT",
      "default_commission": 0.3,
      "date_added": "2020-02-11T11:25:25Z",
      "country": "NG",
      "is_airtime": false,
      "biller_name": "TOP UP ACCOUNT",
      "item_code": "IS211",
      "short_name": "TOP UP ACCOUNT",
      "fee": 100,
      "commission_on_fee": true,
      "label_name": "Account Number",
      "amount": 0
    },
    {
      "id": 433,
      "biller_code": "BIL126",
      "name": "SWIFT TOP UP",
      "default_commission": 0.3,
      "date_added": "2020-02-11T11:25:25Z",
      "country": "NG",
      "is_airtime": false,
      "biller_name": "SWIFT TOP UP",
      "item_code": "IS210",
      "short_name": "SWIFT TOP UP",
      "fee": 100,
      "commission_on_fee": true,
      "label_name": "Account Number",
      "amount": 0
    },
    {
      "id": 434,
      "biller_code": "BIL129",
      "name": "ipNX Family Plan",
      "default_commission": 0.3,
      "date_added": "2020-02-11T11:25:25Z",
      "country": "NG",
      "is_airtime": false,
      "biller_name": "ipNX Family Plan",
      "item_code": "IS213",
      "short_name": "ipNX Family Plan",
      "fee": 100,
      "commission_on_fee": true,
      "label_name": "Account Number",
      "amount": 6300
    },
    {
      "id": 435,
      "biller_code": "BIL129",
      "name": "Starter Basic Plan",
      "default_commission": 0.3,
      "date_added": "2020-02-11T11:25:25Z",
      "country": "NG",
      "is_airtime": false,
      "biller_name": "Starter Basic Plan",
      "item_code": "IS380",
      "short_name": "Starter Basic Plan",
      "fee": 100,
      "commission_on_fee": true,
      "label_name": "Account Number",
      "amount": 7900
    },
    {
      "id": 436,
      "biller_code": "BIL129",
      "name": "Unlimited Starter Plan",
      "default_commission": 0.3,
      "date_added": "2020-02-11T11:25:25Z",
      "country": "NG",
      "is_airtime": false,
      "biller_name": "Unlimited Starter Plan",
      "item_code": "IS381",
      "short_name": "Unlimited Starter Plan",
      "fee": 100,
      "commission_on_fee": true,
      "label_name": "Account Number",
      "amount": 12900
    },
    {
      "id": 437,
      "biller_code": "BIL124",
      "name": "Smile 21gb internet bundle",
      "default_commission": 0.3,
      "date_added": "2020-04-16T03:08:04.39Z",
      "country": "NG",
      "is_airtime": false,
      "biller_name": "SMILE 21GB BUNDLE",
      "item_code": "IS194",
      "short_name": "SMILE 21GB BUNDLE",
      "fee": 100,
      "commission_on_fee": true,
      "label_name": "Account Number",
      "amount": 8190
    },
    {
      "id": 438,
      "biller_code": "BIL124",
      "name": "Smile lite 1.5GB bundle",
      "default_commission": 0.3,
      "date_added": "2020-04-16T03:08:04.39Z",
      "country": "NG",
      "is_airtime": false,
      "biller_name": "SMILE LITE 1.5GB BUNDLE",
      "item_code": "IS195",
      "short_name": "SMILE LITE 1.5GB BUNDLE",
      "fee": 100,
      "commission_on_fee": true,
      "label_name": "Account Number",
      "amount": 1020
    },
    {
      "id": 439,
      "biller_code": "BIL124",
      "name": "Smile 7gb bundle",
      "default_commission": 0.3,
      "date_added": "2020-04-16T03:08:04.39Z",
      "country": "NG",
      "is_airtime": false,
      "biller_name": "SMILE 7GB BUNDLE",
      "item_code": "IS196",
      "short_name": "SMILE 7GB BUNDLE",
      "fee": 100,
      "commission_on_fee": true,
      "label_name": "Account Number",
      "amount": 4090
    },
    {
      "id": 440,
      "biller_code": "BIL124",
      "name": "Smile 15gb data bundle",
      "default_commission": 0.3,
      "date_added": "2020-04-16T03:08:04.39Z",
      "country": "NG",
      "is_airtime": false,
      "biller_name": "SMILE 15GB DATA BUNDLE",
      "item_code": "IS197",
      "short_name": "SMILE 15GB DATA BUNDLE",
      "fee": 100,
      "commission_on_fee": true,
      "label_name": "Account Number",
      "amount": 6140
    },
    {
      "id": 441,
      "biller_code": "BIL124",
      "name": "SMILE 1GB Flexi Daily Data Plan 1 Day",
      "default_commission": 0.3,
      "date_added": "2020-04-16T03:08:04.39Z",
      "country": "NG",
      "is_airtime": false,
      "biller_name": "SMILE 1GB Flexi Daily Data Plan 1 Day",
      "item_code": "IS198",
      "short_name": "SMILE 1GB Flexi Daily Data Plan 1 Day",
      "fee": 100,
      "commission_on_fee": true,
      "label_name": "Account Number",
      "amount": 350
    },
    {
      "id": 442,
      "biller_code": "BIL124",
      "name": "SMILE 2GB Flexi Weekly Data Plan 7 Days",
      "default_commission": 0.3,
      "date_added": "2020-04-16T03:08:04.39Z",
      "country": "NG",
      "is_airtime": false,
      "biller_name": "SMILE 2GB Flexi Weekly Data Plan 7 Days",
      "item_code": "IS199",
      "short_name": "SMILE 2GB Flexi Weekly Data Plan 7 Days",
      "fee": 100,
      "commission_on_fee": true,
      "label_name": "Account Number",
      "amount": 1020
    },
    {
      "id": 443,
      "biller_code": "BIL124",
      "name": "Smile 30GB Anytime Data Plan 60 Days bundle",
      "default_commission": 0.3,
      "date_added": "2020-04-16T03:08:04.39Z",
      "country": "NG",
      "is_airtime": false,
      "biller_name": "SMILE 30GB Bumpa Data Plan 60 Days",
      "item_code": "IS200",
      "short_name": "SMILE 30GB Bumpa Data Plan 60 Days",
      "fee": 100,
      "commission_on_fee": true,
      "label_name": "Account Number",
      "amount": 15350
    },
    {
      "id": 444,
      "biller_code": "BIL124",
      "name": "Smile 60GB Anytime Data Plan 90 Days bundle",
      "default_commission": 0.3,
      "date_added": "2020-04-16T03:08:04.39Z",
      "country": "NG",
      "is_airtime": false,
      "biller_name": "SMILE 60GB BumpaValue Data Plan 90 Days",
      "item_code": "IS201",
      "short_name": "SMILE 60GB BumpaValue Data Plan 90 Days",
      "fee": 100,
      "commission_on_fee": true,
      "label_name": "Account Number",
      "amount": 30700
    },
    {
      "id": 445,
      "biller_code": "BIL124",
      "name": "Smile 80GB Anytime Data Plan 120 Days bundle",
      "default_commission": 0.3,
      "date_added": "2020-04-16T03:08:04.39Z",
      "country": "NG",
      "is_airtime": false,
      "biller_name": "SMILE 80GB BumpaValue Plan 120 Days",
      "item_code": "IS202",
      "short_name": "SMILE 80GB BumpaValue Plan 120 Days",
      "fee": 100,
      "commission_on_fee": true,
      "label_name": "Account Number",
      "amount": 50000
    },
    {
      "id": 446,
      "biller_code": "BIL124",
      "name": "Smile 2GB MidNite Plan",
      "default_commission": 0.3,
      "date_added": "2020-04-16T03:08:04.39Z",
      "country": "NG",
      "is_airtime": false,
      "biller_name": "SMILE 2GB MidNite Plan",
      "item_code": "IS203",
      "short_name": "SMILE 2GB MidNite Plan",
      "fee": 100,
      "commission_on_fee": true,
      "label_name": "Account Number",
      "amount": 1020
    },
    {
      "id": 447,
      "biller_code": "BIL124",
      "name": "Smile 3GB MidNite Plan bundle",
      "default_commission": 0.3,
      "date_added": "2020-04-16T03:08:04.39Z",
      "country": "NG",
      "is_airtime": false,
      "biller_name": "SMILE 3GB MidNite Plan",
      "item_code": "IS204",
      "short_name": "SMILE 3GB MidNite Plan",
      "fee": 100,
      "commission_on_fee": true,
      "label_name": "Account Number",
      "amount": 1530
    },
    {
      "id": 448,
      "biller_code": "BIL124",
      "name": "Smile 3GB Weekend Plan",
      "default_commission": 0.3,
      "date_added": "2020-04-16T03:08:04.39Z",
      "country": "NG",
      "is_airtime": false,
      "biller_name": "SMILE 3GB Weekend Plan",
      "item_code": "IS205",
      "short_name": "SMILE 3GB Weekend Plan",
      "fee": 100,
      "commission_on_fee": true,
      "label_name": "Account Number",
      "amount": 1530
    },
    {
      "id": 449,
      "biller_code": "BIL124",
      "name": "Smile 3GB Data Bundle",
      "default_commission": 0.3,
      "date_added": "2020-04-16T03:08:04.39Z",
      "country": "NG",
      "is_airtime": false,
      "biller_name": "SMILE 3GB Data Bundle",
      "item_code": "IS206",
      "short_name": "SMILE 3GB Data Bundle",
      "fee": 100,
      "commission_on_fee": true,
      "label_name": "Account Number",
      "amount": 3000
    },
    {
      "id": 450,
      "biller_code": "BIL124",
      "name": "Smile 10GB Data Bundle",
      "default_commission": 0.3,
      "date_added": "2020-04-16T03:08:04.39Z",
      "country": "NG",
      "is_airtime": false,
      "biller_name": "SMILE 10GB Data Bundle",
      "item_code": "IS207",
      "short_name": "SMILE 10GB Data Bundle",
      "fee": 100,
      "commission_on_fee": true,
      "label_name": "Account Number",
      "amount": 9000
    },
    {
      "id": 451,
      "biller_code": "BIL124",
      "name": "Smile 50GB Data Bundle",
      "default_commission": 0.3,
      "date_added": "2020-04-16T03:08:04.39Z",
      "country": "NG",
      "is_airtime": false,
      "biller_name": "SMILE 50GB Data Bundle",
      "item_code": "IS208",
      "short_name": "SMILE 50GB Data Bundle",
      "fee": 100,
      "commission_on_fee": true,
      "label_name": "Account Number",
      "amount": 36850
    },
    {
      "id": 452,
      "biller_code": "BIL124",
      "name": "Smile UnlimitedLite Plan",
      "default_commission": 0.3,
      "date_added": "2020-04-16T03:08:04.39Z",
      "country": "NG",
      "is_airtime": false,
      "biller_name": "Smile UnlimitedLite Plan",
      "item_code": "IS222",
      "short_name": "Smile UnlimitedLite Plan",
      "fee": 100,
      "commission_on_fee": true,
      "label_name": "Account Number",
      "amount": 10230
    },
    {
      "id": 453,
      "biller_code": "BIL124",
      "name": "Unlimited Access Bundle",
      "default_commission": 0.3,
      "date_added": "2020-04-16T03:08:04.39Z",
      "country": "NG",
      "is_airtime": false,
      "biller_name": "SMILE - Unlimited Premium ",
      "item_code": "IS273",
      "short_name": "SMILE - Unlimited Premium ",
      "fee": 100,
      "commission_on_fee": true,
      "label_name": "Account Number",
      "amount": 19800
    },
    {
      "id": 454,
      "biller_code": "BIL124",
      "name": "100GB Data Bundle ",
      "default_commission": 0.3,
      "date_added": "2020-04-16T03:08:04.39Z",
      "country": "NG",
      "is_airtime": false,
      "biller_name": "SMILE - 100GB Data Bundle ",
      "item_code": "IS274",
      "short_name": "SMILE - 100GB Data Bundle ",
      "fee": 100,
      "commission_on_fee": true,
      "label_name": "Account Number",
      "amount": 71650
    },
    {
      "id": 455,
      "biller_code": "BIL124",
      "name": "200GB Data Bundle ",
      "default_commission": 0.3,
      "date_added": "2020-04-16T03:08:04.39Z",
      "country": "NG",
      "is_airtime": false,
      "biller_name": "SMILE - 200GB Data Bundle ",
      "item_code": "IS275",
      "short_name": "SMILE - 200GB Data Bundle ",
      "fee": 100,
      "commission_on_fee": true,
      "label_name": "Account Number",
      "amount": 138200
    }
  ]

  export default internet