let power = [
    {
      "id": 264,
      "biller_code": "BIL158",
      "name": "Prepaid Topup",
      "default_commission": 0.1,
      "date_added": "2019-07-29T18:21:23.127Z",
      "country": "UG",
      "is_airtime": false,
      "biller_name": "Prepaid Topup",
      "item_code": "UB288",
      "short_name": "Prepaid Topup",
      "fee": 100,
      "commission_on_fee": true,
      "label_name": "Meter Number",
      "amount": 0
    },
    {
      "id": 265,
      "biller_code": "BIL158",
      "name": "PostPaid Top up",
      "default_commission": 0.1,
      "date_added": "2019-07-29T18:21:23.127Z",
      "country": "UG",
      "is_airtime": false,
      "biller_name": "PostPaid Top up",
      "item_code": "UB289",
      "short_name": "PostPaid Top up",
      "fee": 100,
      "commission_on_fee": true,
      "label_name": "Meter Number",
      "amount": 0
    },
    {
      "id": 266,
      "biller_code": "BIL159",
      "name": "NWSC Top up",
      "default_commission": 0.1,
      "date_added": "2019-07-29T18:22:54.003Z",
      "country": "UG",
      "is_airtime": false,
      "biller_name": "NWSC Top up",
      "item_code": "UB290",
      "short_name": "NWSC Top up",
      "fee": 100,
      "commission_on_fee": true,
      "label_name": "NWSC Number",
      "amount": 1000
    },
    {
      "id": 267,
      "biller_code": "BIL112",
      "name": "EKO DISCO ELECTRICITY BILLS FOR PREPAID CLIENTS",
      "default_commission": 0.3,
      "date_added": "2020-02-11T11:09:48.087Z",
      "country": "NG",
      "is_airtime": false,
      "biller_name": "EKEDC PREPAID TOPUP",
      "item_code": "UB157",
      "short_name": "EKEDC PREPAID TOPUP",
      "fee": 100,
      "commission_on_fee": true,
      "label_name": "Meter Number",
      "amount": 0
    },
    {
      "id": 268,
      "biller_code": "BIL112",
      "name": "EKO Disco postpaid bills",
      "default_commission": 0.3,
      "date_added": "2020-02-11T11:09:48.087Z",
      "country": "NG",
      "is_airtime": false,
      "biller_name": "EKEDC POSTPAID TOPUP",
      "item_code": "UB158",
      "short_name": "EKEDC POSTPAID TOPUP",
      "fee": 100,
      "commission_on_fee": true,
      "label_name": "Meter Number",
      "amount": 0
    },
    {
      "id": 269,
      "biller_code": "BIL113",
      "name": "IKEDC Prepaid topup",
      "default_commission": 0.3,
      "date_added": "2020-02-11T11:09:48.087Z",
      "country": "NG",
      "is_airtime": false,
      "biller_name": "IKEDC  PREPAID TOP UP",
      "item_code": "UB159",
      "short_name": "IKEDC  PREPAID TOP UP",
      "fee": 100,
      "commission_on_fee": true,
      "label_name": "Meter Number",
      "amount": 0
    },
    {
      "id": 270,
      "biller_code": "BIL113",
      "name": "IKEDC post-paid bill payment",
      "default_commission": 0.3,
      "date_added": "2020-02-11T11:09:48.087Z",
      "country": "NG",
      "is_airtime": false,
      "biller_name": "IKEDC  POSTPAID TOP UP",
      "item_code": "UB160",
      "short_name": "IKEDC  POSTPAID TOP UP",
      "fee": 100,
      "commission_on_fee": true,
      "label_name": "Meter Number",
      "amount": 0
    },
    {
      "id": 271,
      "biller_code": "BIL114",
      "name": "IBADAN DISCO ELECTRICITY PREPAID TOP UP",
      "default_commission": 0.3,
      "date_added": "2020-02-11T11:09:48.087Z",
      "country": "NG",
      "is_airtime": false,
      "biller_name": "IBADAN DISCO ELECTRICITY PREPAID TOP UP",
      "item_code": "UB161",
      "short_name": "IBADAN DISCO ELECTRICITY PREPAID TOP UP",
      "fee": 100,
      "commission_on_fee": true,
      "label_name": "Meter Number",
      "amount": 0
    },
    {
      "id": 272,
      "biller_code": "BIL114",
      "name": "IBADAN DISCO ELECTRICITY POSTPAID TOPUP",
      "default_commission": 0.3,
      "date_added": "2020-02-11T11:09:48.087Z",
      "country": "NG",
      "is_airtime": false,
      "biller_name": "IBADAN DISCO ELECTRICITY POSTPAID TOPUP",
      "item_code": "UB162",
      "short_name": "IBADAN DISCO ELECTRICITY POSTPAID TOPUP",
      "fee": 100,
      "commission_on_fee": true,
      "label_name": "Meter Number",
      "amount": 0
    },
    {
      "id": 273,
      "biller_code": "BIL115",
      "name": "ENUGU DISCO ELECTRIC BILLS PREPAID TOPUP",
      "default_commission": 0.3,
      "date_added": "2020-02-11T11:09:48.087Z",
      "country": "NG",
      "is_airtime": false,
      "biller_name": "ENUGU DISCO ELECTRIC BILLS PREPAID TOPUP",
      "item_code": "UB163",
      "short_name": "ENUGU DISCO ELECTRIC BILLS PREPAID TOPUP",
      "fee": 100,
      "commission_on_fee": true,
      "label_name": "Meter Number",
      "amount": 0
    },
    {
      "id": 274,
      "biller_code": "BIL115",
      "name": "ENUGU DISCO ELECTRIC BILLS POSTPAID TOPUP",
      "default_commission": 0.3,
      "date_added": "2020-02-11T11:09:48.087Z",
      "country": "NG",
      "is_airtime": false,
      "biller_name": "ENUGU DISCO ELECTRIC BILLS POSTPAID TOPUP",
      "item_code": "UB164",
      "short_name": "ENUGU DISCO ELECTRIC BILLS POSTPAID TOPUP",
      "fee": 100,
      "commission_on_fee": true,
      "label_name": "Meter Number",
      "amount": 0
    },
    {
      "id": 275,
      "biller_code": "BIL116",
      "name": "PHC DISCO POSTPAID TOPUP",
      "default_commission": 0.3,
      "date_added": "2020-02-11T11:09:48.087Z",
      "country": "NG",
      "is_airtime": false,
      "biller_name": "PHC DISCO POSTPAID TOPUP",
      "item_code": "UB165",
      "short_name": "PHC DISCO POSTPAID TOPUP",
      "fee": 100,
      "commission_on_fee": true,
      "label_name": "Meter Number",
      "amount": 0
    },
    {
      "id": 276,
      "biller_code": "BIL117",
      "name": "BENIN DISCO POSTPAID TOPUP",
      "default_commission": 0.3,
      "date_added": "2020-02-11T11:09:48.087Z",
      "country": "NG",
      "is_airtime": false,
      "biller_name": "BENIN DISCO POSTPAID TOPUP",
      "item_code": "UB166",
      "short_name": "BENIN DISCO POSTPAID TOPUP",
      "fee": 100,
      "commission_on_fee": true,
      "label_name": "Meter Number",
      "amount": 0
    },
    {
      "id": 277,
      "biller_code": "BIL117",
      "name": "BENIN DISCO PREPAID TOPUP",
      "default_commission": 0.3,
      "date_added": "2020-02-11T11:09:48.087Z",
      "country": "NG",
      "is_airtime": false,
      "biller_name": "BENIN DISCO PREPAID TOPUP",
      "item_code": "UB167",
      "short_name": "BENIN DISCO PREPAID TOPUP",
      "fee": 100,
      "commission_on_fee": true,
      "label_name": "Meter Number",
      "amount": 0
    },
    {
      "id": 278,
      "biller_code": "BIL118",
      "name": "YOLA DISCO TOPUP",
      "default_commission": 0.3,
      "date_added": "2020-02-11T11:09:48.087Z",
      "country": "NG",
      "is_airtime": false,
      "biller_name": "YOLA DISCO TOPUP",
      "item_code": "UB168",
      "short_name": "YOLA DISCO TOPUP",
      "fee": 100,
      "commission_on_fee": true,
      "label_name": "Meter Number",
      "amount": 0
    },
    {
      "id": 279,
      "biller_code": "BIL120",
      "name": "KANO DISCO PREPAID TOPUP",
      "default_commission": 0.3,
      "date_added": "2020-02-11T11:09:48.087Z",
      "country": "NG",
      "is_airtime": false,
      "biller_name": "KANO DISCO PREPAID TOPUP",
      "item_code": "UB169",
      "short_name": "KANO DISCO PREPAID TOPUP",
      "fee": 100,
      "commission_on_fee": true,
      "label_name": "Meter Number",
      "amount": 0
    },
    {
      "id": 280,
      "biller_code": "BIL120",
      "name": "KANO DISCO POSTPAID TOPUP",
      "default_commission": 0.3,
      "date_added": "2020-02-11T11:09:48.087Z",
      "country": "NG",
      "is_airtime": false,
      "biller_name": "KANO DISCO POSTPAID TOPUP",
      "item_code": "UB170",
      "short_name": "KANO DISCO POSTPAID TOPUP",
      "fee": 100,
      "commission_on_fee": true,
      "label_name": "Meter Number",
      "amount": 0
    },
    {
      "id": 16868,
      "biller_code": "BIL191",
      "name": "KPLC PREPAID",
      "default_commission": 0.1,
      "date_added": "2020-04-26T20:03:46.727Z",
      "country": "KE",
      "is_airtime": false,
      "biller_name": "KPLC PREPAID",
      "item_code": "UB501",
      "short_name": "KPLC PREPAID",
      "fee": 20,
      "commission_on_fee": true,
      "label_name": "Meter Number",
      "amount": 0
    },
    {
      "id": 16869,
      "biller_code": "BIL191",
      "name": "KPLC POSTPAID",
      "default_commission": 0.1,
      "date_added": "2020-04-26T20:03:46.727Z",
      "country": "KE",
      "is_airtime": false,
      "biller_name": "KPLC POSTPAID",
      "item_code": "UB502",
      "short_name": "KPLC POSTPAID",
      "fee": 20,
      "commission_on_fee": true,
      "label_name": "Meter Number",
      "amount": 0
    },
    {
      "id": 16870,
      "biller_code": "BIL194",
      "name": "NAIROBI WATER",
      "default_commission": 0.1,
      "date_added": "2020-04-26T20:03:46.727Z",
      "country": "KE",
      "is_airtime": false,
      "biller_name": "NAIROBI WATER",
      "item_code": "UB505",
      "short_name": "NAIROBI WATER",
      "fee": 20,
      "commission_on_fee": true,
      "label_name": "Meter Number",
      "amount": 0
    }
  ]

  export default power